import { defineConfig } from '@adonisjs/vite'

const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this directory. The path should
   * be relative from the application root.
   *
   * It lives in a dedicated `vite/` subfolder (NOT bare `public/assets`) on
   * purpose: the AdonisJS Vite plugin empties this directory on every build.
   * Our hand-written design system (base.css, theme.js, fonts, …) lives in
   * `public/assets` and must survive `node ace build` — including inside the
   * Docker image — so Vite gets its own sandbox to wipe.
   */
  buildDirectory: 'public/assets/vite',

  /**
   * The path to the manifest file generated by the
   * "vite build" command.
   */
  manifestFile: 'public/assets/vite/.vite/manifest.json',

  /**
   * Feel free to change the value of the "assetsUrl" to
   * point to a CDN in production.
   */
  assetsUrl: '/assets/vite',

  scriptAttributes: {
    defer: true,
  },
})

export default viteBackendConfig
